---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: jgeusebroek/ubuntu2004-molecule
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
verifier:
  name: testinfra
  directory: ../resources/tests/
scenario:
  test_sequence:
    - dependency
    # - lint TODO - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence TODO - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
#   flake8