---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-express"
      include_role:
        name: "ansible-express"
      vars:
        express_system_user: "express"
        express_system_group: "www-data"
        express_system_user_home: "/home/{{ express_system_user }}"
        express_node_version: 10.x
        express_git_url: "https://github.com/onaio/reveal-frontend"
        express_git_version: "v0.4.0-rc11"
        express_app_settings:
          NODE_ENV: "production"
