---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install prerequisites
      apt:
        name: " {{ item }} "
        update_cache: true
        state: present
      loop:
        # - gpg-agent
        - curl
        # - tmux
        # - vim
